# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='basic.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x62\x61sic.proto\"\x1c\n\x0bRequestItem\x12\r\n\x05items\x18\x01 \x01(\x0c\"\x1d\n\nItemResult\x12\x0f\n\x07results\x18\x01 \x01(\x0c\x32:\n\x0c\x42\x61sicService\x12*\n\rInferenceItem\x12\x0c.RequestItem\x1a\x0b.ItemResultb\x06proto3'
)




_REQUESTITEM = _descriptor.Descriptor(
  name='RequestItem',
  full_name='RequestItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='RequestItem.items', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=43,
)


_ITEMRESULT = _descriptor.Descriptor(
  name='ItemResult',
  full_name='ItemResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='ItemResult.results', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['RequestItem'] = _REQUESTITEM
DESCRIPTOR.message_types_by_name['ItemResult'] = _ITEMRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestItem = _reflection.GeneratedProtocolMessageType('RequestItem', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTITEM,
  '__module__' : 'basic_pb2'
  # @@protoc_insertion_point(class_scope:RequestItem)
  })
_sym_db.RegisterMessage(RequestItem)

ItemResult = _reflection.GeneratedProtocolMessageType('ItemResult', (_message.Message,), {
  'DESCRIPTOR' : _ITEMRESULT,
  '__module__' : 'basic_pb2'
  # @@protoc_insertion_point(class_scope:ItemResult)
  })
_sym_db.RegisterMessage(ItemResult)



_BASICSERVICE = _descriptor.ServiceDescriptor(
  name='BasicService',
  full_name='BasicService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=76,
  serialized_end=134,
  methods=[
  _descriptor.MethodDescriptor(
    name='InferenceItem',
    full_name='BasicService.InferenceItem',
    index=0,
    containing_service=None,
    input_type=_REQUESTITEM,
    output_type=_ITEMRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BASICSERVICE)

DESCRIPTOR.services_by_name['BasicService'] = _BASICSERVICE

# @@protoc_insertion_point(module_scope)
